# Generated by Django 3.2.9 on 2021-12-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Error'), (2, 'Finished')], default=0)),
                ('is_celery_task_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Group Report',
                'verbose_name_plural': 'Group Reports',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ReportGroupTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Error'), (2, 'Finished')], default=0)),
                ('retry', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('finished_dt', models.DateTimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportgroup')),
            ],
            options={
                'verbose_name': 'Group Report Task Log',
                'verbose_name_plural': 'Group Reports Task Log',
                'ordering': ('created_dt',),
            },
        ),
    ]
