# Generated by Django 3.2.9 on 2021-12-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgrouptasklog',
            name='finished_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
