# Generated by Django 3.2.9 on 2021-12-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportgrouptasklog_finished_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportChord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Error'), (2, 'Finished')], default=0)),
                ('is_celery_task_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chord Report',
                'verbose_name_plural': 'Chord Reports',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ReportChordTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Error'), (2, 'Finished')], default=0)),
                ('retry', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('finished_dt', models.DateTimeField(null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportchord')),
            ],
            options={
                'verbose_name': 'Chord Report Task Log',
                'verbose_name_plural': 'Chord Reports Task Log',
                'ordering': ('created_dt',),
            },
        ),
    ]
